import type { BodyId, CelestialBody, ComponentCategory, RocketComponent } from './types';

export const COMPONENT_CATEGORIES: ComponentCategory[] = [
  'Structure',
  'Tanks',
  'Engines',
  'Control',
  'Science',
  'Landing',
  'Payload',
];

export const COMPONENTS: RocketComponent[] = [
  {
    id: 'nose-aero',
    name: 'Aero Nose Cone',
    category: 'Structure',
    description: 'Low drag cone for stable ascent.',
    mass: 0.8,
    cost: 40,
    size: 'medium',
    drag: -0.12,
  },
  {
    id: 'capsule-mk1',
    name: 'Mk1 Command Capsule',
    category: 'Control',
    description: 'Crew control pod with basic reaction wheels.',
    mass: 2.2,
    cost: 140,
    size: 'medium',
    drag: 0.03,
  },
  {
    id: 'guidance-ring',
    name: 'Guidance Ring',
    category: 'Control',
    description: 'Improves steering response during ascent and orbital burns.',
    mass: 0.5,
    cost: 95,
    size: 'medium',
  },
  {
    id: 'tank-small',
    name: 'Small Fuel Tank',
    category: 'Tanks',
    description: 'Light tank for upper stages.',
    mass: 1.1,
    fuel: 280,
    cost: 110,
    size: 'small',
    drag: 0.02,
  },
  {
    id: 'tank-core',
    name: 'Core Fuel Tank',
    category: 'Tanks',
    description: 'Reliable kerolox tank; stacks and merges with matching tanks.',
    mass: 2.8,
    fuel: 850,
    cost: 260,
    size: 'medium',
    drag: 0.04,
  },
  {
    id: 'tank-heavy',
    name: 'Heavy Fuel Tank',
    category: 'Tanks',
    description: 'Wide high-capacity tank for deep-space launches.',
    mass: 5.6,
    fuel: 1850,
    cost: 560,
    size: 'large',
    drag: 0.08,
    unlockCost: 600,
  },
  {
    id: 'tank-hydrolox',
    name: 'Hydrolox Cryo Tank',
    category: 'Tanks',
    description: 'Expensive lightweight fuel tank with excellent delta-v.',
    mass: 3.1,
    fuel: 2300,
    cost: 980,
    size: 'large',
    drag: 0.06,
    unlockCost: 1600,
  },
  {
    id: 'engine-orbiter',
    name: 'Orbiter Engine',
    category: 'Engines',
    description: 'Balanced vacuum engine for orbit insertion.',
    mass: 1.6,
    thrust: 360,
    isp: 330,
    cost: 240,
    size: 'medium',
    drag: 0.02,
  },
  {
    id: 'engine-booster',
    name: 'Solid Booster',
    category: 'Engines',
    description: 'Cheap raw thrust for the first minute of flight.',
    mass: 2.4,
    fuel: 620,
    thrust: 690,
    isp: 240,
    cost: 310,
    size: 'medium',
    drag: 0.07,
  },
  {
    id: 'engine-vector',
    name: 'Vector Engine',
    category: 'Engines',
    description: 'High-control main engine for heavy launchers.',
    mass: 2.8,
    thrust: 1120,
    isp: 310,
    cost: 880,
    size: 'large',
    unlockCost: 1200,
  },
  {
    id: 'engine-nuclear',
    name: 'Nuclear Transfer Engine',
    category: 'Engines',
    description: 'Low thrust, superb efficiency for interplanetary burns.',
    mass: 3.4,
    thrust: 260,
    isp: 830,
    cost: 1600,
    size: 'medium',
    unlockCost: 2500,
  },
  {
    id: 'separator-stage',
    name: 'Stage Separator',
    category: 'Structure',
    description: 'Creates a new stage and drops spent mass.',
    mass: 0.35,
    cost: 80,
    size: 'medium',
    stageSeparator: true,
  },
  {
    id: 'separator-booster',
    name: 'Booster Separator',
    category: 'Structure',
    description: 'Radial release clamp for side boosters.',
    mass: 0.25,
    cost: 65,
    size: 'small',
    boosterSeparator: true,
  },
  {
    id: 'parachute',
    name: 'Drogue Parachute',
    category: 'Landing',
    description: 'Slows terminal velocity for Earth, Venus, and Mars landings.',
    mass: 0.28,
    cost: 90,
    size: 'small',
    parachute: true,
    drag: -0.08,
  },
  {
    id: 'heat-shield',
    name: 'Ceramic Heat Shield',
    category: 'Landing',
    description: 'Prevents burn-up during atmospheric re-entry.',
    mass: 0.9,
    cost: 160,
    size: 'medium',
    heatShield: true,
    drag: 0.04,
  },
  {
    id: 'heat-shield-ablative',
    name: 'Ablative Heat Shield',
    category: 'Landing',
    description: 'Higher temperature margin for Venus and high-speed returns.',
    mass: 1.2,
    cost: 520,
    size: 'large',
    heatShield: true,
    drag: 0.02,
    unlockCost: 950,
  },
  {
    id: 'landing-feet',
    name: 'Extendable Landing Feet',
    category: 'Landing',
    description: 'Absorbs low-speed landings on rocky worlds.',
    mass: 0.7,
    cost: 180,
    size: 'medium',
    landingFeet: true,
    drag: 0.02,
  },
  {
    id: 'wheel-pair',
    name: 'Rover Wheels',
    category: 'Landing',
    description: 'Small deployable wheel pack for rover bodies.',
    mass: 0.35,
    cost: 140,
    size: 'small',
    wheels: true,
  },
  {
    id: 'satellite-bus',
    name: 'Satellite Bus',
    category: 'Science',
    description: 'Payload for commercial orbit deployment contracts.',
    mass: 0.85,
    cost: 320,
    size: 'small',
    satellite: true,
  },
  {
    id: 'solar-panels',
    name: 'Expandable Solar Panels',
    category: 'Science',
    description: 'Power for satellites, rovers, and deep-space probes.',
    mass: 0.45,
    cost: 210,
    size: 'small',
    solar: true,
  },
  {
    id: 'rover-bay',
    name: 'Rover Bay',
    category: 'Payload',
    description: 'Carries a surface rover that can deploy after landing.',
    mass: 1.9,
    cost: 540,
    size: 'large',
    roverBay: true,
    drag: 0.04,
  },
  {
    id: 'cargo-lab',
    name: 'Sample Lab',
    category: 'Payload',
    description: 'Doubles Astrobucks earned from EVA and rover rocks.',
    mass: 1.3,
    cost: 800,
    size: 'medium',
    unlockCost: 700,
  },
];

export const CELESTIAL_BODIES: CelestialBody[] = [
  {
    id: 'sun',
    name: 'Sun',
    kind: 'star',
    texture: '/textures/2k_sun.jpg',
    radiusKm: 696340,
    gravity: 274,
    atmosphere: false,
    orbitRadius: 0,
    orbitDays: 1,
    color: '#ffd36f',
    initialAccess: true,
  },
  {
    id: 'mercury',
    name: 'Mercury',
    kind: 'planet',
    texture: '/textures/2k_mercury.jpg',
    radiusKm: 2439,
    gravity: 3.7,
    atmosphere: false,
    orbitRadius: 10,
    orbitDays: 88,
    color: '#a8977b',
    unlockCost: 450,
    canLand: true,
  },
  {
    id: 'venus',
    name: 'Venus',
    kind: 'planet',
    texture: '/textures/2k_venus_surface.jpg',
    radiusKm: 6051,
    gravity: 8.87,
    atmosphere: true,
    orbitRadius: 16,
    orbitDays: 225,
    color: '#d8aa63',
    initialAccess: true,
    canLand: true,
  },
  {
    id: 'earth',
    name: 'Earth',
    kind: 'planet',
    texture: '/textures/2k_earth_daymap.jpg',
    radiusKm: 6371,
    gravity: 9.81,
    atmosphere: true,
    orbitRadius: 23,
    orbitDays: 365,
    color: '#4f9cff',
    initialAccess: true,
    canLand: true,
  },
  {
    id: 'moon',
    name: 'The Moon',
    kind: 'moon',
    texture: '/textures/2k_moon.jpg',
    radiusKm: 1737,
    gravity: 1.62,
    atmosphere: false,
    orbitRadius: 3.3,
    orbitDays: 27,
    color: '#bfc3c7',
    parent: 'earth',
    initialAccess: true,
    canLand: true,
  },
  {
    id: 'mars',
    name: 'Mars',
    kind: 'planet',
    texture: '/textures/2k_mars.jpg',
    radiusKm: 3389,
    gravity: 3.71,
    atmosphere: true,
    orbitRadius: 33,
    orbitDays: 687,
    color: '#c86c43',
    initialAccess: true,
    canLand: true,
  },
  {
    id: 'phobos',
    name: 'Phobos',
    kind: 'moon',
    texture: '/textures/2k_moon.jpg',
    radiusKm: 11,
    gravity: 0.006,
    atmosphere: false,
    orbitRadius: 1.5,
    orbitDays: 0.3,
    color: '#9b8b76',
    parent: 'mars',
    initialAccess: true,
    canLand: true,
  },
  {
    id: 'deimos',
    name: 'Deimos',
    kind: 'moon',
    texture: '/textures/2k_moon.jpg',
    radiusKm: 6,
    gravity: 0.003,
    atmosphere: false,
    orbitRadius: 2.2,
    orbitDays: 1.2,
    color: '#aa9c86',
    parent: 'mars',
    initialAccess: true,
    canLand: true,
  },
  {
    id: 'jupiter',
    name: 'Jupiter',
    kind: 'planet',
    texture: '/textures/2k_jupiter.jpg',
    radiusKm: 69911,
    gravity: 24.79,
    atmosphere: true,
    orbitRadius: 58,
    orbitDays: 4333,
    color: '#d4ac80',
    unlockCost: 1200,
  },
  {
    id: 'io',
    name: 'Io',
    kind: 'moon',
    texture: '/textures/2k_moon.jpg',
    radiusKm: 1821,
    gravity: 1.79,
    atmosphere: false,
    orbitRadius: 4.2,
    orbitDays: 1.8,
    color: '#d6bd62',
    parent: 'jupiter',
    unlockCost: 1200,
    canLand: true,
  },
  {
    id: 'europa',
    name: 'Europa',
    kind: 'moon',
    texture: '/textures/2k_moon.jpg',
    radiusKm: 1560,
    gravity: 1.31,
    atmosphere: false,
    orbitRadius: 5.4,
    orbitDays: 3.5,
    color: '#d8d2c5',
    parent: 'jupiter',
    unlockCost: 1200,
    canLand: true,
  },
  {
    id: 'ganymede',
    name: 'Ganymede',
    kind: 'moon',
    texture: '/textures/2k_moon.jpg',
    radiusKm: 2634,
    gravity: 1.43,
    atmosphere: false,
    orbitRadius: 6.7,
    orbitDays: 7.1,
    color: '#8f8378',
    parent: 'jupiter',
    unlockCost: 1200,
    canLand: true,
  },
  {
    id: 'callisto',
    name: 'Callisto',
    kind: 'moon',
    texture: '/textures/2k_moon.jpg',
    radiusKm: 2410,
    gravity: 1.24,
    atmosphere: false,
    orbitRadius: 8.4,
    orbitDays: 16.7,
    color: '#776b62',
    parent: 'jupiter',
    unlockCost: 1200,
    canLand: true,
  },
  {
    id: 'saturn',
    name: 'Saturn',
    kind: 'planet',
    texture: '/textures/2k_saturn.jpg',
    radiusKm: 58232,
    gravity: 10.44,
    atmosphere: true,
    orbitRadius: 78,
    orbitDays: 10759,
    color: '#d8c28d',
    unlockCost: 2100,
  },
  {
    id: 'titan',
    name: 'Titan',
    kind: 'moon',
    texture: '/textures/2k_moon.jpg',
    radiusKm: 2575,
    gravity: 1.35,
    atmosphere: true,
    orbitRadius: 5.8,
    orbitDays: 16,
    color: '#b58f50',
    parent: 'saturn',
    unlockCost: 2100,
    canLand: true,
  },
  {
    id: 'enceladus',
    name: 'Enceladus',
    kind: 'moon',
    texture: '/textures/2k_moon.jpg',
    radiusKm: 252,
    gravity: 0.113,
    atmosphere: false,
    orbitRadius: 3.8,
    orbitDays: 1.4,
    color: '#e8edf0',
    parent: 'saturn',
    unlockCost: 2100,
    canLand: true,
  },
  {
    id: 'rhea',
    name: 'Rhea',
    kind: 'moon',
    texture: '/textures/2k_moon.jpg',
    radiusKm: 764,
    gravity: 0.264,
    atmosphere: false,
    orbitRadius: 4.7,
    orbitDays: 4.5,
    color: '#c2bbb0',
    parent: 'saturn',
    unlockCost: 2100,
    canLand: true,
  },
  {
    id: 'iapetus',
    name: 'Iapetus',
    kind: 'moon',
    texture: '/textures/2k_moon.jpg',
    radiusKm: 735,
    gravity: 0.223,
    atmosphere: false,
    orbitRadius: 7,
    orbitDays: 79,
    color: '#9a8f83',
    parent: 'saturn',
    unlockCost: 2100,
    canLand: true,
  },
  {
    id: 'uranus',
    name: 'Uranus',
    kind: 'planet',
    texture: '/textures/2k_uranus.jpg',
    radiusKm: 25362,
    gravity: 8.69,
    atmosphere: true,
    orbitRadius: 96,
    orbitDays: 30687,
    color: '#9bdbe6',
    unlockCost: 3100,
  },
  {
    id: 'neptune',
    name: 'Neptune',
    kind: 'planet',
    texture: '/textures/2k_neptune.jpg',
    radiusKm: 24622,
    gravity: 11.15,
    atmosphere: true,
    orbitRadius: 112,
    orbitDays: 60190,
    color: '#4d7ce8',
    unlockCost: 3900,
  },
  {
    id: 'triton',
    name: 'Triton',
    kind: 'moon',
    texture: '/textures/2k_moon.jpg',
    radiusKm: 1353,
    gravity: 0.779,
    atmosphere: false,
    orbitRadius: 4,
    orbitDays: 5.9,
    color: '#d3cfc5',
    parent: 'neptune',
    unlockCost: 3900,
    canLand: true,
  },
  {
    id: 'pluto',
    name: 'Pluto',
    kind: 'dwarf',
    texture: '/textures/pluto_color_map.jpg',
    radiusKm: 1188,
    gravity: 0.62,
    atmosphere: false,
    orbitRadius: 130,
    orbitDays: 90560,
    color: '#d9b9a7',
    unlockCost: 4700,
    canLand: true,
  },
];

export const BODY_BY_ID = Object.fromEntries(
  CELESTIAL_BODIES.map((body) => [body.id, body]),
) as Record<BodyId, CelestialBody>;

export const MARKET_UNLOCKS = CELESTIAL_BODIES.filter(
  (body) => body.unlockCost && !body.parent,
);

export const FIRST_ACCESS: BodyId[] = CELESTIAL_BODIES.filter((body) => body.initialAccess).map(
  (body) => body.id,
);

export const REQUIRED_TEXTURE_SOURCES = [
  {
    label: 'Solar System Scope planetary textures',
    url: 'https://www.solarsystemscope.com/textures/',
  },
  {
    label: 'JPL Pluto color map PIA11707',
    url: 'https://www.jpl.nasa.gov/images/pia11707-pluto-color-map/',
  },
];
